//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuocViet_2022601829.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public string Loai { get; set; }
        public double GiaBan { get; set; }
    }
}
